{% set name = "grad-cam" %}
{% set version = "1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grad-cam-{{ version }}.tar.gz
  sha256: 5a10b742330387813c3673bc4b20ad83dac580326460febfc5d58d713be52855

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - opencv >=4.1
    - pytorch >=1.7.1
    - torchvision >=0.8.2
    - tqdm >=4.42
    - ttach >=0.0.3
    - pillow
    - numpy
    - matplotlib-base
    - scikit-learn
    # Note: regro-cf-autotick-bot suggested to add "timm"
    # refer to: https://github.com/conda-forge/grad-cam-feedstock/pull/3
    - timm
    ## Note: Necessary for supporting "opencv"
    #  A. "mesa-libGL" should be present in "yum_requirements.txt".
    #  B. "libgdal" should be added to "meta.yaml:requirements:run".
    - libgdal

test:
  imports:
    - pytorch_grad_cam
    - pytorch_grad_cam.utils

about:
  home: https://github.com/jacobgil/pytorch-grad-cam
  summary: |
    Many Class Activation Map methods implemented in Pytorch.
    Including Grad-CAM, Grad-CAM++, Score-CAM, Ablation-CAM
    and XGrad-CAM.
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/jacobgil/pytorch-grad-cam
  dev_url: https://github.com/jacobgil/pytorch-grad-cam

extra:
  recipe-maintainers:
    - sugatoray
    - jacobgil
    - anjos
